version: "3.9"

services:
  storage: 
    image: redis
    volumes: 
        - ./data:/data
  books:
    build: ./src
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - REDIS_URL=redis://storage
    volumes:
      - ./data:/app-data
    depends_on:
      - storage

